<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst;</TargetFrameworks>

		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>PRG1_MAUI_ERP_Activum</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>PRG1_MAUI_ERP_Activum</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.prg1_maui_erp_activum</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.11" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Model\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Styles\ActivumTheme.xaml.cs">
	    <DependentUpon>ActivumTheme.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Auth\LoginPage.xaml.cs">
	    <DependentUpon>LoginPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Customer\CustomerHomePage.xaml.cs">
	    <DependentUpon>CustomerHomePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Employee\CustomersPage.xaml.cs">
	    <DependentUpon>CustomersPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Employee\EmployeeHomePage.xaml.cs">
	    <DependentUpon>EmployeeHomePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Employee\RiskSettingsPage.xaml.cs">
	    <DependentUpon>RiskSettingsPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Customer\CustomerRegisterPage.xaml.cs">
	    <DependentUpon>CustomerRegisterPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Insurance\InsuranceRegisterPage.xaml.cs">
	    <DependentUpon>InsuranceRegisterPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Shared\HeaderView.xaml.cs">
	    <DependentUpon>HeaderView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Shared\LogoutPage.xaml.cs">
	    <DependentUpon>LogoutPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Shared\HelpPage.xaml.cs">
	    <DependentUpon>HelpPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Shared\SharedHeader.xaml.cs">
	    <DependentUpon>SharedHeader.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Shared\StartPage.xaml.cs">
	    <DependentUpon>StartPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Tools\PerDiemPage.xaml.cs">
	    <DependentUpon>PerDiemPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="View\Tools\SalaryBonusPage.xaml.cs">
	    <DependentUpon>SalaryBonusPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Resources\Styles\ActivumTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Auth\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Customer\CustomerHomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\CustomFlyoutView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Employee\EmployeeHomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Employee\RiskSettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Customer\CustomerRegisterPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Insurance\InsuranceRegisterPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\AboutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Customer\CalculatorPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Employee\CustomersPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Customer\InsurancePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\HeaderView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\LogoutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\HelpPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\SharedHeader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\PerDiemPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\SalaryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\StartPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Shared\SupportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Employee\ToolsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Tools\PerDiemPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\Tools\SalaryBonusPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
